### ISSUE TITLE
Doesn't work for my init.js script, can you expand a little bit on this line? AST fails

### ISSUE THREAD

**Issue by XBeg9** [MiddleSchoolStudent/PerimeterX-solver#1]
https://github.com/MiddleSchoolStudent/PerimeterX-solver/blame/3bba90eb35cdb4fcb033e3037bb8f10b190648dd/readable/eps-p.md#L6

**Comment by MSTU0** [comment]
@XBeg9 

I don't know what init.js is, eps-p's de-obfuscation code executes in astexplorer according to this config:

<img width="1508" src="https://github.com/user-attachments/assets/88dee09d-9097-424f-b07a-2d3c2273460d">

**Comment by XBeg9** [comment]
yea, normally it's main.js or init.js.... looks like for your script they use different name. Anyway, what you posted (AST transformations doesn't work) for this [one](https://www.alaskaair.com/AlXMT4Ma/init.js) as an example.

**Comment by MSTU0** [comment]
> yea, normally it's main.js or init.js.... looks like for your script they use different name. Anyway, what you posted (AST transformations doesn't work) for this [one](https://www.alaskaair.com/AlXMT4Ma/init.js) as an example.

I see. This file requires separate deobfuscation method. It is not difficult. Just refer to my previous one

**Comment by MSTU0** [comment]
> yea, normally it's main.js or init.js.... looks like for your script they use different name. Anyway, what you posted (AST transformations doesn't work) for this [one](https://www.alaskaair.com/AlXMT4Ma/init.js) as an example.

@XBeg9 well, solve by this commit. Have fun! https://github.com/MiddleSchoolStudent/PerimeterX-solver/commit/fe7b071f16fff2a0c6641e531f225babcf25e228

**Comment by XBeg9** [comment]
@MiddleSchoolStudent 🇺🇦 Слава Україні ;) дякую
